name: 刷步数

on:
  schedule:
    - cron: '11 1 * * *'    # 北京 09:11
    - cron: '17 2 * * *'    # 北京 10:17
    - cron: '23 3 * * *'    # 北京 11:23
    - cron: '29 5 * * *'    # 北京 13:29
    - cron: '35 7 * * *'    # 北京 15:35
    - cron: '41 9 * * *'    # 北京 17:41
    - cron: '47 11 * * *'   # 北京 19:47
    - cron: '53 13 * * *'   # 北京 21:53
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout codes
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.PAT }} #此处PAT需要申请，教程详见：README
      - name: Update system and install zsh
        run: |
          sudo -E apt-get -qq update
          sudo -E apt-get install zsh -y
          
      - name: 初始化Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"
          
      - name: 开始
        env:
            CONFIG: ${{ secrets.CONFIG }}
            AES_KEY: ${{ secrets.AES_KEY }}
            PUSH_PLUS_TOKEN: ${{ secrets.PUSH_PLUS_TOKEN }}
        run: |
          pip3 install -r requirements.txt
          python3 main.py

      - name: persist tokens
        run: |
          git config user.name github-actions
          git config user.email github-actions@users.noreply.github.com
          git add .
          if ! git diff --cached --quiet; then
            git commit -m "persist tokens trigger by ${{ github.event_name }}"
            git push origin master
          else
            echo "No changes to commit, skip"
          fi
